sudo: required
services: 
    - docker

before_install:
    - docker build -t sunny199/docker-react -f Dockerfile.dev .

## tell how to test
script:
    - docker run sunny199/docker-react npm run test -- --coverage 
deploy:
     provider: elasticbeanstalk
     region: "us-west-2"
     app: "docker-react"
     env: "Docker-env"
     bucket-name: 
     bucket-path: "docker-react"
     on: 
       branch: master
     access_key_id : $AWS_ACCESS_KEY
     secret_access_key: 
            secure: "$AWS_SECRET_KEY"              